languageCode = "en-gb"
theme = "beautifulhugo"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseurl = "https://thoeni.io/"
canonifyurls = true
title = "to, err := human()"
author = "Antonio Troina"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
googleAnalytics = "UA-74480113-1"
disqusShortname = "thoeni-io"

[params]
    subtitle = "Another blog the world could do without."
    logo = "images/avatar.jpg"
    favicon = "images/favicon.ico"
    dateFormat = "January 2, 2006"
    commit = true
    rss = true
    comments = true
    name = "Antonio Troina"
    #gcse = "000555443219246452905:kk1yklqhyf4"

[Author]
  name = "Antonio Troina"
  email = "thoeni@gmail.com"
  googleplus = "+thoeni"
  github = "thoeni"
  twitter = "antoniotroina"
  stackoverflow = "users/2728768/thoeni"
  linkedin = "antoniotroina"
  spotify = "1110847262"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Resources"
    url = "/page/resources"
    weight = 2

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    weight = 3

[[menu.main]]
    parent = "projects"
    name = "Slack Tube Service"
    url = "/project/slack-tube-service/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about"
    weight = 4

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 5
